apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp 
    spec:
      containers:
      - name: myserver
        image: 094175769936.dkr.ecr.eu-central-1.amazonaws.com/ideabank:latest
        ports:
        - containerPort: 3000
        
---

apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp 
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
